const fs = require('fs');

const banner =
  '// This code was generated by a tool.\n// Changes to this file may cause incorrect behavior and will be lost if\n// the code is regenerated.\n\n// tslint:disable\n';

module.exports = function (content, ...args) {
  const { resourcePath } = this;
  const callback = this.async();

  const matchClassNames = /^export var ([^=]+?) =/gm;

  let declaration = '';
  let matchResult = null;
  while ((matchResult = matchClassNames.exec(content)) !== null) {
    declaration += `export const ${matchResult[1]}: string;\n`;
  }

  fs.writeFile(
    `${resourcePath}.d.ts`,
    `${banner}\n${declaration}`,
    function () {
      callback(null, content, ...args);
    }
  );
};
